upgrade gradle and add test report

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -30,6 +30,12 @@ jobs:
       - name: Run tests for all modules
         run: ./gradlew test
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+
       - name: Generate jacoco reports
         run: ./gradlew jacocoTestReport
 
